### ISSUE TITLE
Identify (meta)data requirements from use cases

### ISSUE THREAD

**Issue by mroos** [ejp-rd-vp/DistributedAnalysis#1]
Matching use cases
1. Transcriptome catalogs (MOCK, modeled after GEO, etc.)
2. Variant & clinical information sources (MOCK, modeled after LUMC, RUMC, Sweden-FEGA) 
3. Public resources linkable to genome+clinical information (REAL: drugs, pathways)

Relevance for onboarding
1. Test of EJP RD metadata model, new requirements for L3 cases

**Comment by mroos** [comment]
Transcriptomics case

- [ ] co-development with ELIXIR WP: requirements for metadata from ELIXIR RD WP2 can be used
- [ ] Daphne created template schema, will link this.


Requirements for genome+clinical+public linkable data use case - extended prediction
Flash cards have been defined

To do: 

- [ ] Align with Wolmar
- [ ] Eric, Nura, Andra, Wolmar to work out case, work on patient profiles (create with FHIR tool?)


Where to put outputs?

- [ ] Andra's executable book can be on Github
- [ ] put it in a private space on Github

**Comment by wna-se** [comment]
Next steps: List of example resources and corresponding items from the use case flashcards being worked on, including the related information needs and their representations as (meta)data:
* **1+MG example:** A clinical professional treating a patient wants to know if a variant observed in a patient has been reported in other patients in order to assess if the variant is likely to be the cause of an observed phenotype. See mapping: https://docs.google.com/document/d/199AfeVQUk6ff35DEzPGzIlMwrDi8Uemx-vjwv6d4iKc/edit
 * Genomic variant information
 * Phenotype information
* **Delta tissue example:** …
* **Duchenne example:** …



![Image](https://github.com/ejp-rd-vp/DistributedAnalysis/assets/1221165/6836c65b-0ec0-4c5f-ae6b-b36f41decb93)

**Comment by wna-se** [comment]
Will adapt the work we did to map the use case to the CDE models implementation to the new CARE-SM implementations over the next week. Some elements that would be useful to WGS/Variant sequence-related scenarios are missing (see updates from https://github.com/ejp-rd-vp/DistributedAnalysis/issues/29)
